# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      az artifacts universal download \
      --organization "https://dev.azure.com/josielbruk/" \
      --feed "josielbruk" \
      --name "my-first-package" \
      --version "0.0.1" \
      --path $(System.ArtifactsDirectory)

  - script: |
      echo "Listing files"
      ls $(System.ArtifactsDirectory)
    displayName: 'Run a one-line script'


