trigger: none
  # - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure-SC'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        # echo $(System.AccessToken) | az devops login
        # az artifacts universal download --organization "https://dev.azure.com/josielbruk" --feed "josielbruk" --name "my-first-package" --version "*" --path "app"
        az acr login -n josielacr.azurecr.io
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)  

  # - task: UniversalPackages@0
  #   displayName: Download a Universal Package
  #   inputs:
  #     command: download
  #     vstsFeed: 'josielbruk'
  #     vstsFeedPackage: 'my-first-package'
  #     vstsPackageVersion: '0.0.37'
  #     downloadDirectory: '$(Build.SourcesDirectory)\DownloadedFromArtifact'
  
  # - script: |
  #     echo "Listing files"
  #     tree
  #   displayName: "Listing the content of the current folder"
  
  - task: AzureFunctionAppContainer@1
    inputs:
      azureSubscription: 'e421e2dc-1a19-4a76-8bc5-310b8c5f03ef' # string. Required. Azure subscription. 
      appName: containerfunctionjosiel # string. Required. App name. 
      deployToSlotOrASE: true #false # boolean. Deploy to Slot or App Service Environment. Default: false.
      resourceGroupName: containerFunction # string. Required when deployToSlotOrASE = true. Resource group. 
      slotName: 'dev' # string. Required when deployToSlotOrASE = true. Slot. Default: production.
      imageName: josielacr.azurecr.io/addaggregationdata:latest # string. Required. Image name. 
      #containerCommand: # string. Startup command. 
    # Application and Configuration Settings
      #appSettings: # string. App settings. 
      #configurationStrings: # string. Configuration settings.