trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  # authenticate with Azure using OIDC

  - script: |
      echo "Listing files"
      ls
    displayName: "Listing the content of the current folder"
