# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UniversalPackages@0
    inputs:
      command: 'download'
      downloadDirectory: '$(System.ArtifactsDirectory)' # The directory to place the downloaded package
      feed: 'josielbruk' # The name of your feed
      # view: 'myView' # The view within the feed to download the package from
      name: 'my-first-package' # The name of the package to download
      version: '0.0.1' # The version of the package to download

  - script: |
      echo "Listing files"
      ls $(System.ArtifactsDirectory)
    displayName: 'Run a one-line script'


