trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Azure-SC'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo $(System.AccessToken) | az devops login
        az artifacts universal download --organization "https://dev.azure.com/josielbruk" --feed "josielbruk" --name "my-first-package" --version "*" --path "./App/"
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - script: |
      echo "Listing files"
      tree
    displayName: "Listing the content of the current folder"