name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'                 # set this to the .NET Core version to use
  TAG: ${{ github.RUN_NUMBER }}

on:
  push:
    branches: [ "main" ]
    paths: 
      - 'app/**'
  pull_request:
    branches: [ "main" ]
    paths: 
      - 'app/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # build:
  # runs-on: ubuntu-latest
  job:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
    - uses: actions/checkout@v4

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ github.workspace }}/app/src/RazorPagesTestSample/RazorPagesTestSample.sln
      shell: /usr/bin/bash -e {0}
      # env:
      #   AZURE_WEBAPP_NAME: your-app-name
      #   AZURE_WEBAPP_PACKAGE_PATH: .
      #   DOTNET_VERSION: 6.0.x
      #   DOTNET_ROOT: /home/runner/.dotnet

    - name: Build with dotnet
      run: dotnet build ./app/src/RazorPagesTestSample/RazorPagesTestSample.csproj

    - name: dotnet test
      run: dotnet test ./app/src/RazorPagesTestSample/RazorPagesTestSample.csproj --configuration Release

    - name: Publish
      run: dotnet publish ./app/src/RazorPagesTestSample/RazorPagesTestSample.csproj -c Release --output ./publish/

    - name: Publish Artifact to Azure DevOps
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az artifacts universal publish --organization "https://dev.azure.com/josielbruk/" --project "newapp" --scope project --feed "josielbruk" --name "my-first-package" --version "0.0.1" --description "Just a Package Description" --path "./publish/"